# Generated by Django 3.0.8 on 2020-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('postdate', models.DateTimeField(auto_now_add=True)),
                ('videofile', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='')),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('camera', models.ImageField(blank=True, upload_to='photos/')),
                ('msg', models.TextField()),
                ('seen', models.IntegerField(default=1)),
                ('likes', models.IntegerField(default=0)),
                ('unlike', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'WAITING'), ('confirm', 'CONFIRM'), ('rejected', 'REJECTED')], default='waiting', max_length=20)),
            ],
        ),
    ]
