# Generated by Django 3.0.8 on 2020-07-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='videofile',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='data',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
